/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWsRouteImport } from './routes/w.$ws'
import { Route as WWsIndexRouteImport } from './routes/w.$ws.index'
import { Route as WWsAlertsRouteImport } from './routes/w.$ws.alerts'
import { Route as WWsApprovalsRouteImport } from './routes/w.$ws.approvals'
import { Route as WWsBudgetsRouteImport } from './routes/w.$ws.budgets'
import { Route as WWsClosuresRouteImport } from './routes/w.$ws.closures'
import { Route as WWsExperimentsRouteImport } from './routes/w.$ws.experiments'
import { Route as WWsSearchRouteImport } from './routes/w.$ws.search'
import { Route as WWsSourcesRouteImport } from './routes/w.$ws.sources'
import { Route as WWsTargetsRouteImport } from './routes/w.$ws.targets'
import { Route as WWsAdminNamingRouteImport } from './routes/w.$ws.admin.naming'
import { Route as WWsAdminPoliciesRouteImport } from './routes/w.$ws.admin.policies'
import { Route as WWsAdminRegistryRouteImport } from './routes/w.$ws.admin.registry'
import { Route as WWsAdminRolesRouteImport } from './routes/w.$ws.admin.roles'
import { Route as WWsAdminRulesRouteImport } from './routes/w.$ws.admin.rules'
import { Route as WWsAdminSourcesRouteImport } from './routes/w.$ws.admin.sources'
import { Route as WWsAdminTagsRouteImport } from './routes/w.$ws.admin.tags'
import { Route as WWsAdminTemplatesRouteImport } from './routes/w.$ws.admin.templates'
import { Route as WWsAdminToursRouteImport } from './routes/w.$ws.admin.tours'
import { Route as WWsApprovalsIndexRouteImport } from './routes/w.$ws.approvals.index'
import { Route as WWsApprovalsIdRouteImport } from './routes/w.$ws.approvals.$id'
import { Route as WWsExperimentsIndexRouteImport } from './routes/w.$ws.experiments.index'
import { Route as WWsExperimentsIdRouteImport } from './routes/w.$ws.experiments.$id'
import { Route as WWsSourcesIndexRouteImport } from './routes/w.$ws.sources.index'
import { Route as WWsSourcesManualRouteImport } from './routes/w.$ws.sources.manual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWsRoute = WWsRouteImport.update({
  id: '/w/$ws',
  path: '/w/$ws',
  getParentRoute: () => rootRouteImport,
} as any)
const WWsIndexRoute = WWsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAlertsRoute = WWsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WWsRoute,
} as any)
const WWsApprovalsRoute = WWsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WWsRoute,
} as any)
const WWsBudgetsRoute = WWsBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => WWsRoute,
} as any)
const WWsClosuresRoute = WWsClosuresRouteImport.update({
  id: '/closures',
  path: '/closures',
  getParentRoute: () => WWsRoute,
} as any)
const WWsExperimentsRoute = WWsExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => WWsRoute,
} as any)
const WWsSearchRoute = WWsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => WWsRoute,
} as any)
const WWsSourcesRoute = WWsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => WWsRoute,
} as any)
const WWsTargetsRoute = WWsTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminNamingRoute = WWsAdminNamingRouteImport.update({
  id: '/admin/naming',
  path: '/admin/naming',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminPoliciesRoute = WWsAdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminRegistryRoute = WWsAdminRegistryRouteImport.update({
  id: '/admin/registry',
  path: '/admin/registry',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminRolesRoute = WWsAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminRulesRoute = WWsAdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminSourcesRoute = WWsAdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminTagsRoute = WWsAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminTemplatesRoute = WWsAdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => WWsRoute,
} as any)
const WWsAdminToursRoute = WWsAdminToursRouteImport.update({
  id: '/admin/tours',
  path: '/admin/tours',
  getParentRoute: () => WWsRoute,
} as any)
const WWsApprovalsIndexRoute = WWsApprovalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWsApprovalsRoute,
} as any)
const WWsApprovalsIdRoute = WWsApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WWsApprovalsRoute,
} as any)
const WWsExperimentsIndexRoute = WWsExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWsExperimentsRoute,
} as any)
const WWsExperimentsIdRoute = WWsExperimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WWsExperimentsRoute,
} as any)
const WWsSourcesIndexRoute = WWsSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWsSourcesRoute,
} as any)
const WWsSourcesManualRoute = WWsSourcesManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => WWsSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$ws': typeof WWsRouteWithChildren
  '/w/$ws/alerts': typeof WWsAlertsRoute
  '/w/$ws/approvals': typeof WWsApprovalsRouteWithChildren
  '/w/$ws/budgets': typeof WWsBudgetsRoute
  '/w/$ws/closures': typeof WWsClosuresRoute
  '/w/$ws/experiments': typeof WWsExperimentsRouteWithChildren
  '/w/$ws/search': typeof WWsSearchRoute
  '/w/$ws/sources': typeof WWsSourcesRouteWithChildren
  '/w/$ws/targets': typeof WWsTargetsRoute
  '/w/$ws/': typeof WWsIndexRoute
  '/w/$ws/admin/naming': typeof WWsAdminNamingRoute
  '/w/$ws/admin/policies': typeof WWsAdminPoliciesRoute
  '/w/$ws/admin/registry': typeof WWsAdminRegistryRoute
  '/w/$ws/admin/roles': typeof WWsAdminRolesRoute
  '/w/$ws/admin/rules': typeof WWsAdminRulesRoute
  '/w/$ws/admin/sources': typeof WWsAdminSourcesRoute
  '/w/$ws/admin/tags': typeof WWsAdminTagsRoute
  '/w/$ws/admin/templates': typeof WWsAdminTemplatesRoute
  '/w/$ws/admin/tours': typeof WWsAdminToursRoute
  '/w/$ws/approvals/$id': typeof WWsApprovalsIdRoute
  '/w/$ws/experiments/$id': typeof WWsExperimentsIdRoute
  '/w/$ws/sources/manual': typeof WWsSourcesManualRoute
  '/w/$ws/approvals/': typeof WWsApprovalsIndexRoute
  '/w/$ws/experiments/': typeof WWsExperimentsIndexRoute
  '/w/$ws/sources/': typeof WWsSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$ws/alerts': typeof WWsAlertsRoute
  '/w/$ws/budgets': typeof WWsBudgetsRoute
  '/w/$ws/closures': typeof WWsClosuresRoute
  '/w/$ws/search': typeof WWsSearchRoute
  '/w/$ws/targets': typeof WWsTargetsRoute
  '/w/$ws': typeof WWsIndexRoute
  '/w/$ws/admin/naming': typeof WWsAdminNamingRoute
  '/w/$ws/admin/policies': typeof WWsAdminPoliciesRoute
  '/w/$ws/admin/registry': typeof WWsAdminRegistryRoute
  '/w/$ws/admin/roles': typeof WWsAdminRolesRoute
  '/w/$ws/admin/rules': typeof WWsAdminRulesRoute
  '/w/$ws/admin/sources': typeof WWsAdminSourcesRoute
  '/w/$ws/admin/tags': typeof WWsAdminTagsRoute
  '/w/$ws/admin/templates': typeof WWsAdminTemplatesRoute
  '/w/$ws/admin/tours': typeof WWsAdminToursRoute
  '/w/$ws/approvals/$id': typeof WWsApprovalsIdRoute
  '/w/$ws/experiments/$id': typeof WWsExperimentsIdRoute
  '/w/$ws/sources/manual': typeof WWsSourcesManualRoute
  '/w/$ws/approvals': typeof WWsApprovalsIndexRoute
  '/w/$ws/experiments': typeof WWsExperimentsIndexRoute
  '/w/$ws/sources': typeof WWsSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$ws': typeof WWsRouteWithChildren
  '/w/$ws/alerts': typeof WWsAlertsRoute
  '/w/$ws/approvals': typeof WWsApprovalsRouteWithChildren
  '/w/$ws/budgets': typeof WWsBudgetsRoute
  '/w/$ws/closures': typeof WWsClosuresRoute
  '/w/$ws/experiments': typeof WWsExperimentsRouteWithChildren
  '/w/$ws/search': typeof WWsSearchRoute
  '/w/$ws/sources': typeof WWsSourcesRouteWithChildren
  '/w/$ws/targets': typeof WWsTargetsRoute
  '/w/$ws/': typeof WWsIndexRoute
  '/w/$ws/admin/naming': typeof WWsAdminNamingRoute
  '/w/$ws/admin/policies': typeof WWsAdminPoliciesRoute
  '/w/$ws/admin/registry': typeof WWsAdminRegistryRoute
  '/w/$ws/admin/roles': typeof WWsAdminRolesRoute
  '/w/$ws/admin/rules': typeof WWsAdminRulesRoute
  '/w/$ws/admin/sources': typeof WWsAdminSourcesRoute
  '/w/$ws/admin/tags': typeof WWsAdminTagsRoute
  '/w/$ws/admin/templates': typeof WWsAdminTemplatesRoute
  '/w/$ws/admin/tours': typeof WWsAdminToursRoute
  '/w/$ws/approvals/$id': typeof WWsApprovalsIdRoute
  '/w/$ws/experiments/$id': typeof WWsExperimentsIdRoute
  '/w/$ws/sources/manual': typeof WWsSourcesManualRoute
  '/w/$ws/approvals/': typeof WWsApprovalsIndexRoute
  '/w/$ws/experiments/': typeof WWsExperimentsIndexRoute
  '/w/$ws/sources/': typeof WWsSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$ws'
    | '/w/$ws/alerts'
    | '/w/$ws/approvals'
    | '/w/$ws/budgets'
    | '/w/$ws/closures'
    | '/w/$ws/experiments'
    | '/w/$ws/search'
    | '/w/$ws/sources'
    | '/w/$ws/targets'
    | '/w/$ws/'
    | '/w/$ws/admin/naming'
    | '/w/$ws/admin/policies'
    | '/w/$ws/admin/registry'
    | '/w/$ws/admin/roles'
    | '/w/$ws/admin/rules'
    | '/w/$ws/admin/sources'
    | '/w/$ws/admin/tags'
    | '/w/$ws/admin/templates'
    | '/w/$ws/admin/tours'
    | '/w/$ws/approvals/$id'
    | '/w/$ws/experiments/$id'
    | '/w/$ws/sources/manual'
    | '/w/$ws/approvals/'
    | '/w/$ws/experiments/'
    | '/w/$ws/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w/$ws/alerts'
    | '/w/$ws/budgets'
    | '/w/$ws/closures'
    | '/w/$ws/search'
    | '/w/$ws/targets'
    | '/w/$ws'
    | '/w/$ws/admin/naming'
    | '/w/$ws/admin/policies'
    | '/w/$ws/admin/registry'
    | '/w/$ws/admin/roles'
    | '/w/$ws/admin/rules'
    | '/w/$ws/admin/sources'
    | '/w/$ws/admin/tags'
    | '/w/$ws/admin/templates'
    | '/w/$ws/admin/tours'
    | '/w/$ws/approvals/$id'
    | '/w/$ws/experiments/$id'
    | '/w/$ws/sources/manual'
    | '/w/$ws/approvals'
    | '/w/$ws/experiments'
    | '/w/$ws/sources'
  id:
    | '__root__'
    | '/'
    | '/w/$ws'
    | '/w/$ws/alerts'
    | '/w/$ws/approvals'
    | '/w/$ws/budgets'
    | '/w/$ws/closures'
    | '/w/$ws/experiments'
    | '/w/$ws/search'
    | '/w/$ws/sources'
    | '/w/$ws/targets'
    | '/w/$ws/'
    | '/w/$ws/admin/naming'
    | '/w/$ws/admin/policies'
    | '/w/$ws/admin/registry'
    | '/w/$ws/admin/roles'
    | '/w/$ws/admin/rules'
    | '/w/$ws/admin/sources'
    | '/w/$ws/admin/tags'
    | '/w/$ws/admin/templates'
    | '/w/$ws/admin/tours'
    | '/w/$ws/approvals/$id'
    | '/w/$ws/experiments/$id'
    | '/w/$ws/sources/manual'
    | '/w/$ws/approvals/'
    | '/w/$ws/experiments/'
    | '/w/$ws/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWsRoute: typeof WWsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$ws': {
      id: '/w/$ws'
      path: '/w/$ws'
      fullPath: '/w/$ws'
      preLoaderRoute: typeof WWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$ws/': {
      id: '/w/$ws/'
      path: '/'
      fullPath: '/w/$ws/'
      preLoaderRoute: typeof WWsIndexRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/alerts': {
      id: '/w/$ws/alerts'
      path: '/alerts'
      fullPath: '/w/$ws/alerts'
      preLoaderRoute: typeof WWsAlertsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/approvals': {
      id: '/w/$ws/approvals'
      path: '/approvals'
      fullPath: '/w/$ws/approvals'
      preLoaderRoute: typeof WWsApprovalsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/budgets': {
      id: '/w/$ws/budgets'
      path: '/budgets'
      fullPath: '/w/$ws/budgets'
      preLoaderRoute: typeof WWsBudgetsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/closures': {
      id: '/w/$ws/closures'
      path: '/closures'
      fullPath: '/w/$ws/closures'
      preLoaderRoute: typeof WWsClosuresRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/experiments': {
      id: '/w/$ws/experiments'
      path: '/experiments'
      fullPath: '/w/$ws/experiments'
      preLoaderRoute: typeof WWsExperimentsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/search': {
      id: '/w/$ws/search'
      path: '/search'
      fullPath: '/w/$ws/search'
      preLoaderRoute: typeof WWsSearchRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/sources': {
      id: '/w/$ws/sources'
      path: '/sources'
      fullPath: '/w/$ws/sources'
      preLoaderRoute: typeof WWsSourcesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/targets': {
      id: '/w/$ws/targets'
      path: '/targets'
      fullPath: '/w/$ws/targets'
      preLoaderRoute: typeof WWsTargetsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/naming': {
      id: '/w/$ws/admin/naming'
      path: '/admin/naming'
      fullPath: '/w/$ws/admin/naming'
      preLoaderRoute: typeof WWsAdminNamingRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/policies': {
      id: '/w/$ws/admin/policies'
      path: '/admin/policies'
      fullPath: '/w/$ws/admin/policies'
      preLoaderRoute: typeof WWsAdminPoliciesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/registry': {
      id: '/w/$ws/admin/registry'
      path: '/admin/registry'
      fullPath: '/w/$ws/admin/registry'
      preLoaderRoute: typeof WWsAdminRegistryRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/roles': {
      id: '/w/$ws/admin/roles'
      path: '/admin/roles'
      fullPath: '/w/$ws/admin/roles'
      preLoaderRoute: typeof WWsAdminRolesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/rules': {
      id: '/w/$ws/admin/rules'
      path: '/admin/rules'
      fullPath: '/w/$ws/admin/rules'
      preLoaderRoute: typeof WWsAdminRulesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/sources': {
      id: '/w/$ws/admin/sources'
      path: '/admin/sources'
      fullPath: '/w/$ws/admin/sources'
      preLoaderRoute: typeof WWsAdminSourcesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/tags': {
      id: '/w/$ws/admin/tags'
      path: '/admin/tags'
      fullPath: '/w/$ws/admin/tags'
      preLoaderRoute: typeof WWsAdminTagsRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/templates': {
      id: '/w/$ws/admin/templates'
      path: '/admin/templates'
      fullPath: '/w/$ws/admin/templates'
      preLoaderRoute: typeof WWsAdminTemplatesRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/admin/tours': {
      id: '/w/$ws/admin/tours'
      path: '/admin/tours'
      fullPath: '/w/$ws/admin/tours'
      preLoaderRoute: typeof WWsAdminToursRouteImport
      parentRoute: typeof WWsRoute
    }
    '/w/$ws/approvals/': {
      id: '/w/$ws/approvals/'
      path: '/'
      fullPath: '/w/$ws/approvals/'
      preLoaderRoute: typeof WWsApprovalsIndexRouteImport
      parentRoute: typeof WWsApprovalsRoute
    }
    '/w/$ws/approvals/$id': {
      id: '/w/$ws/approvals/$id'
      path: '/$id'
      fullPath: '/w/$ws/approvals/$id'
      preLoaderRoute: typeof WWsApprovalsIdRouteImport
      parentRoute: typeof WWsApprovalsRoute
    }
    '/w/$ws/experiments/': {
      id: '/w/$ws/experiments/'
      path: '/'
      fullPath: '/w/$ws/experiments/'
      preLoaderRoute: typeof WWsExperimentsIndexRouteImport
      parentRoute: typeof WWsExperimentsRoute
    }
    '/w/$ws/experiments/$id': {
      id: '/w/$ws/experiments/$id'
      path: '/$id'
      fullPath: '/w/$ws/experiments/$id'
      preLoaderRoute: typeof WWsExperimentsIdRouteImport
      parentRoute: typeof WWsExperimentsRoute
    }
    '/w/$ws/sources/': {
      id: '/w/$ws/sources/'
      path: '/'
      fullPath: '/w/$ws/sources/'
      preLoaderRoute: typeof WWsSourcesIndexRouteImport
      parentRoute: typeof WWsSourcesRoute
    }
    '/w/$ws/sources/manual': {
      id: '/w/$ws/sources/manual'
      path: '/manual'
      fullPath: '/w/$ws/sources/manual'
      preLoaderRoute: typeof WWsSourcesManualRouteImport
      parentRoute: typeof WWsSourcesRoute
    }
  }
}

interface WWsApprovalsRouteChildren {
  WWsApprovalsIdRoute: typeof WWsApprovalsIdRoute
  WWsApprovalsIndexRoute: typeof WWsApprovalsIndexRoute
}

const WWsApprovalsRouteChildren: WWsApprovalsRouteChildren = {
  WWsApprovalsIdRoute: WWsApprovalsIdRoute,
  WWsApprovalsIndexRoute: WWsApprovalsIndexRoute,
}

const WWsApprovalsRouteWithChildren = WWsApprovalsRoute._addFileChildren(
  WWsApprovalsRouteChildren,
)

interface WWsExperimentsRouteChildren {
  WWsExperimentsIdRoute: typeof WWsExperimentsIdRoute
  WWsExperimentsIndexRoute: typeof WWsExperimentsIndexRoute
}

const WWsExperimentsRouteChildren: WWsExperimentsRouteChildren = {
  WWsExperimentsIdRoute: WWsExperimentsIdRoute,
  WWsExperimentsIndexRoute: WWsExperimentsIndexRoute,
}

const WWsExperimentsRouteWithChildren = WWsExperimentsRoute._addFileChildren(
  WWsExperimentsRouteChildren,
)

interface WWsSourcesRouteChildren {
  WWsSourcesManualRoute: typeof WWsSourcesManualRoute
  WWsSourcesIndexRoute: typeof WWsSourcesIndexRoute
}

const WWsSourcesRouteChildren: WWsSourcesRouteChildren = {
  WWsSourcesManualRoute: WWsSourcesManualRoute,
  WWsSourcesIndexRoute: WWsSourcesIndexRoute,
}

const WWsSourcesRouteWithChildren = WWsSourcesRoute._addFileChildren(
  WWsSourcesRouteChildren,
)

interface WWsRouteChildren {
  WWsAlertsRoute: typeof WWsAlertsRoute
  WWsApprovalsRoute: typeof WWsApprovalsRouteWithChildren
  WWsBudgetsRoute: typeof WWsBudgetsRoute
  WWsClosuresRoute: typeof WWsClosuresRoute
  WWsExperimentsRoute: typeof WWsExperimentsRouteWithChildren
  WWsSearchRoute: typeof WWsSearchRoute
  WWsSourcesRoute: typeof WWsSourcesRouteWithChildren
  WWsTargetsRoute: typeof WWsTargetsRoute
  WWsIndexRoute: typeof WWsIndexRoute
  WWsAdminNamingRoute: typeof WWsAdminNamingRoute
  WWsAdminPoliciesRoute: typeof WWsAdminPoliciesRoute
  WWsAdminRegistryRoute: typeof WWsAdminRegistryRoute
  WWsAdminRolesRoute: typeof WWsAdminRolesRoute
  WWsAdminRulesRoute: typeof WWsAdminRulesRoute
  WWsAdminSourcesRoute: typeof WWsAdminSourcesRoute
  WWsAdminTagsRoute: typeof WWsAdminTagsRoute
  WWsAdminTemplatesRoute: typeof WWsAdminTemplatesRoute
  WWsAdminToursRoute: typeof WWsAdminToursRoute
}

const WWsRouteChildren: WWsRouteChildren = {
  WWsAlertsRoute: WWsAlertsRoute,
  WWsApprovalsRoute: WWsApprovalsRouteWithChildren,
  WWsBudgetsRoute: WWsBudgetsRoute,
  WWsClosuresRoute: WWsClosuresRoute,
  WWsExperimentsRoute: WWsExperimentsRouteWithChildren,
  WWsSearchRoute: WWsSearchRoute,
  WWsSourcesRoute: WWsSourcesRouteWithChildren,
  WWsTargetsRoute: WWsTargetsRoute,
  WWsIndexRoute: WWsIndexRoute,
  WWsAdminNamingRoute: WWsAdminNamingRoute,
  WWsAdminPoliciesRoute: WWsAdminPoliciesRoute,
  WWsAdminRegistryRoute: WWsAdminRegistryRoute,
  WWsAdminRolesRoute: WWsAdminRolesRoute,
  WWsAdminRulesRoute: WWsAdminRulesRoute,
  WWsAdminSourcesRoute: WWsAdminSourcesRoute,
  WWsAdminTagsRoute: WWsAdminTagsRoute,
  WWsAdminTemplatesRoute: WWsAdminTemplatesRoute,
  WWsAdminToursRoute: WWsAdminToursRoute,
}

const WWsRouteWithChildren = WWsRoute._addFileChildren(WWsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWsRoute: WWsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
