export interface IsoCountry {
  code: string;
  label: string;
  regionCode: "AMER" | "LATAM" | "EMEA" | "APAC";
}

/** ISO 3166-1 alpha-2 assigned codes. regionCode is the default registry parent. */
export const ISO_COUNTRIES: readonly IsoCountry[] = [
  { code: "AF", label: "Afghanistan", regionCode: "APAC" },
  { code: "AX", label: "Åland Islands", regionCode: "EMEA" },
  { code: "AL", label: "Albania", regionCode: "EMEA" },
  { code: "DZ", label: "Algeria", regionCode: "EMEA" },
  { code: "AS", label: "American Samoa", regionCode: "APAC" },
  { code: "AD", label: "Andorra", regionCode: "EMEA" },
  { code: "AO", label: "Angola", regionCode: "EMEA" },
  { code: "AI", label: "Anguilla", regionCode: "LATAM" },
  { code: "AQ", label: "Antarctica", regionCode: "AMER" },
  { code: "AG", label: "Antigua and Barbuda", regionCode: "LATAM" },
  { code: "AR", label: "Argentina", regionCode: "LATAM" },
  { code: "AM", label: "Armenia", regionCode: "EMEA" },
  { code: "AW", label: "Aruba", regionCode: "LATAM" },
  { code: "AU", label: "Australia", regionCode: "APAC" },
  { code: "AT", label: "Austria", regionCode: "EMEA" },
  { code: "AZ", label: "Azerbaijan", regionCode: "EMEA" },
  { code: "BS", label: "Bahamas", regionCode: "LATAM" },
  { code: "BH", label: "Bahrain", regionCode: "EMEA" },
  { code: "BD", label: "Bangladesh", regionCode: "APAC" },
  { code: "BB", label: "Barbados", regionCode: "LATAM" },
  { code: "BY", label: "Belarus", regionCode: "EMEA" },
  { code: "BE", label: "Belgium", regionCode: "EMEA" },
  { code: "BZ", label: "Belize", regionCode: "LATAM" },
  { code: "BJ", label: "Benin", regionCode: "EMEA" },
  { code: "BM", label: "Bermuda", regionCode: "AMER" },
  { code: "BT", label: "Bhutan", regionCode: "APAC" },
  { code: "BO", label: "Bolivia, Plurinational State of", regionCode: "LATAM" },
  { code: "BQ", label: "Bonaire, Sint Eustatius and Saba", regionCode: "LATAM" },
  { code: "BA", label: "Bosnia and Herzegovina", regionCode: "EMEA" },
  { code: "BW", label: "Botswana", regionCode: "EMEA" },
  { code: "BV", label: "Bouvet Island", regionCode: "LATAM" },
  { code: "BR", label: "Brazil", regionCode: "LATAM" },
  { code: "IO", label: "British Indian Ocean Territory", regionCode: "EMEA" },
  { code: "BN", label: "Brunei Darussalam", regionCode: "APAC" },
  { code: "BG", label: "Bulgaria", regionCode: "EMEA" },
  { code: "BF", label: "Burkina Faso", regionCode: "EMEA" },
  { code: "BI", label: "Burundi", regionCode: "EMEA" },
  { code: "CV", label: "Cabo Verde", regionCode: "EMEA" },
  { code: "KH", label: "Cambodia", regionCode: "APAC" },
  { code: "CM", label: "Cameroon", regionCode: "EMEA" },
  { code: "CA", label: "Canada", regionCode: "AMER" },
  { code: "KY", label: "Cayman Islands", regionCode: "LATAM" },
  { code: "CF", label: "Central African Republic", regionCode: "EMEA" },
  { code: "TD", label: "Chad", regionCode: "EMEA" },
  { code: "CL", label: "Chile", regionCode: "LATAM" },
  { code: "CN", label: "China", regionCode: "APAC" },
  { code: "CX", label: "Christmas Island", regionCode: "APAC" },
  { code: "CC", label: "Cocos (Keeling) Islands", regionCode: "APAC" },
  { code: "CO", label: "Colombia", regionCode: "LATAM" },
  { code: "KM", label: "Comoros", regionCode: "EMEA" },
  { code: "CG", label: "Congo", regionCode: "EMEA" },
  { code: "CD", label: "Congo, Democratic Republic of the", regionCode: "EMEA" },
  { code: "CK", label: "Cook Islands", regionCode: "APAC" },
  { code: "CR", label: "Costa Rica", regionCode: "LATAM" },
  { code: "CI", label: "Côte d'Ivoire", regionCode: "EMEA" },
  { code: "HR", label: "Croatia", regionCode: "EMEA" },
  { code: "CU", label: "Cuba", regionCode: "LATAM" },
  { code: "CW", label: "Curaçao", regionCode: "LATAM" },
  { code: "CY", label: "Cyprus", regionCode: "EMEA" },
  { code: "CZ", label: "Czechia", regionCode: "EMEA" },
  { code: "DK", label: "Denmark", regionCode: "EMEA" },
  { code: "DJ", label: "Djibouti", regionCode: "EMEA" },
  { code: "DM", label: "Dominica", regionCode: "LATAM" },
  { code: "DO", label: "Dominican Republic", regionCode: "LATAM" },
  { code: "EC", label: "Ecuador", regionCode: "LATAM" },
  { code: "EG", label: "Egypt", regionCode: "EMEA" },
  { code: "SV", label: "El Salvador", regionCode: "LATAM" },
  { code: "GQ", label: "Equatorial Guinea", regionCode: "EMEA" },
  { code: "ER", label: "Eritrea", regionCode: "EMEA" },
  { code: "EE", label: "Estonia", regionCode: "EMEA" },
  { code: "SZ", label: "Eswatini", regionCode: "EMEA" },
  { code: "ET", label: "Ethiopia", regionCode: "EMEA" },
  { code: "FK", label: "Falkland Islands (Malvinas)", regionCode: "LATAM" },
  { code: "FO", label: "Faroe Islands", regionCode: "EMEA" },
  { code: "FJ", label: "Fiji", regionCode: "APAC" },
  { code: "FI", label: "Finland", regionCode: "EMEA" },
  { code: "FR", label: "France", regionCode: "EMEA" },
  { code: "GF", label: "French Guiana", regionCode: "LATAM" },
  { code: "PF", label: "French Polynesia", regionCode: "APAC" },
  { code: "TF", label: "French Southern Territories", regionCode: "EMEA" },
  { code: "GA", label: "Gabon", regionCode: "EMEA" },
  { code: "GM", label: "Gambia", regionCode: "EMEA" },
  { code: "GE", label: "Georgia", regionCode: "EMEA" },
  { code: "DE", label: "Germany", regionCode: "EMEA" },
  { code: "GH", label: "Ghana", regionCode: "EMEA" },
  { code: "GI", label: "Gibraltar", regionCode: "EMEA" },
  { code: "GR", label: "Greece", regionCode: "EMEA" },
  { code: "GL", label: "Greenland", regionCode: "AMER" },
  { code: "GD", label: "Grenada", regionCode: "LATAM" },
  { code: "GP", label: "Guadeloupe", regionCode: "LATAM" },
  { code: "GU", label: "Guam", regionCode: "APAC" },
  { code: "GT", label: "Guatemala", regionCode: "LATAM" },
  { code: "GG", label: "Guernsey", regionCode: "EMEA" },
  { code: "GN", label: "Guinea", regionCode: "EMEA" },
  { code: "GW", label: "Guinea-Bissau", regionCode: "EMEA" },
  { code: "GY", label: "Guyana", regionCode: "LATAM" },
  { code: "HT", label: "Haiti", regionCode: "LATAM" },
  { code: "HM", label: "Heard Island and McDonald Islands", regionCode: "APAC" },
  { code: "VA", label: "Holy See", regionCode: "EMEA" },
  { code: "HN", label: "Honduras", regionCode: "LATAM" },
  { code: "HK", label: "Hong Kong", regionCode: "APAC" },
  { code: "HU", label: "Hungary", regionCode: "EMEA" },
  { code: "IS", label: "Iceland", regionCode: "EMEA" },
  { code: "IN", label: "India", regionCode: "APAC" },
  { code: "ID", label: "Indonesia", regionCode: "APAC" },
  { code: "IR", label: "Iran, Islamic Republic of", regionCode: "APAC" },
  { code: "IQ", label: "Iraq", regionCode: "EMEA" },
  { code: "IE", label: "Ireland", regionCode: "EMEA" },
  { code: "IM", label: "Isle of Man", regionCode: "EMEA" },
  { code: "IL", label: "Israel", regionCode: "EMEA" },
  { code: "IT", label: "Italy", regionCode: "EMEA" },
  { code: "JM", label: "Jamaica", regionCode: "LATAM" },
  { code: "JP", label: "Japan", regionCode: "APAC" },
  { code: "JE", label: "Jersey", regionCode: "EMEA" },
  { code: "JO", label: "Jordan", regionCode: "EMEA" },
  { code: "KZ", label: "Kazakhstan", regionCode: "APAC" },
  { code: "KE", label: "Kenya", regionCode: "EMEA" },
  { code: "KI", label: "Kiribati", regionCode: "APAC" },
  { code: "KP", label: "Korea, Democratic People's Republic of", regionCode: "APAC" },
  { code: "KR", label: "Korea, Republic of", regionCode: "APAC" },
  { code: "KW", label: "Kuwait", regionCode: "EMEA" },
  { code: "KG", label: "Kyrgyzstan", regionCode: "APAC" },
  { code: "LA", label: "Lao People's Democratic Republic", regionCode: "APAC" },
  { code: "LV", label: "Latvia", regionCode: "EMEA" },
  { code: "LB", label: "Lebanon", regionCode: "EMEA" },
  { code: "LS", label: "Lesotho", regionCode: "EMEA" },
  { code: "LR", label: "Liberia", regionCode: "EMEA" },
  { code: "LY", label: "Libya", regionCode: "EMEA" },
  { code: "LI", label: "Liechtenstein", regionCode: "EMEA" },
  { code: "LT", label: "Lithuania", regionCode: "EMEA" },
  { code: "LU", label: "Luxembourg", regionCode: "EMEA" },
  { code: "MO", label: "Macao", regionCode: "APAC" },
  { code: "MG", label: "Madagascar", regionCode: "EMEA" },
  { code: "MW", label: "Malawi", regionCode: "EMEA" },
  { code: "MY", label: "Malaysia", regionCode: "APAC" },
  { code: "MV", label: "Maldives", regionCode: "APAC" },
  { code: "ML", label: "Mali", regionCode: "EMEA" },
  { code: "MT", label: "Malta", regionCode: "EMEA" },
  { code: "MH", label: "Marshall Islands", regionCode: "APAC" },
  { code: "MQ", label: "Martinique", regionCode: "LATAM" },
  { code: "MR", label: "Mauritania", regionCode: "EMEA" },
  { code: "MU", label: "Mauritius", regionCode: "EMEA" },
  { code: "YT", label: "Mayotte", regionCode: "EMEA" },
  { code: "MX", label: "Mexico", regionCode: "LATAM" },
  { code: "FM", label: "Micronesia, Federated States of", regionCode: "APAC" },
  { code: "MD", label: "Moldova, Republic of", regionCode: "EMEA" },
  { code: "MC", label: "Monaco", regionCode: "EMEA" },
  { code: "MN", label: "Mongolia", regionCode: "APAC" },
  { code: "ME", label: "Montenegro", regionCode: "EMEA" },
  { code: "MS", label: "Montserrat", regionCode: "LATAM" },
  { code: "MA", label: "Morocco", regionCode: "EMEA" },
  { code: "MZ", label: "Mozambique", regionCode: "EMEA" },
  { code: "MM", label: "Myanmar", regionCode: "APAC" },
  { code: "NA", label: "Namibia", regionCode: "EMEA" },
  { code: "NR", label: "Nauru", regionCode: "APAC" },
  { code: "NP", label: "Nepal", regionCode: "APAC" },
  { code: "NL", label: "Netherlands, Kingdom of the", regionCode: "EMEA" },
  { code: "NC", label: "New Caledonia", regionCode: "APAC" },
  { code: "NZ", label: "New Zealand", regionCode: "APAC" },
  { code: "NI", label: "Nicaragua", regionCode: "LATAM" },
  { code: "NE", label: "Niger", regionCode: "EMEA" },
  { code: "NG", label: "Nigeria", regionCode: "EMEA" },
  { code: "NU", label: "Niue", regionCode: "APAC" },
  { code: "NF", label: "Norfolk Island", regionCode: "APAC" },
  { code: "MK", label: "North Macedonia", regionCode: "EMEA" },
  { code: "MP", label: "Northern Mariana Islands", regionCode: "APAC" },
  { code: "NO", label: "Norway", regionCode: "EMEA" },
  { code: "OM", label: "Oman", regionCode: "EMEA" },
  { code: "PK", label: "Pakistan", regionCode: "APAC" },
  { code: "PW", label: "Palau", regionCode: "APAC" },
  { code: "PS", label: "Palestine, State of", regionCode: "EMEA" },
  { code: "PA", label: "Panama", regionCode: "LATAM" },
  { code: "PG", label: "Papua New Guinea", regionCode: "APAC" },
  { code: "PY", label: "Paraguay", regionCode: "LATAM" },
  { code: "PE", label: "Peru", regionCode: "LATAM" },
  { code: "PH", label: "Philippines", regionCode: "APAC" },
  { code: "PN", label: "Pitcairn", regionCode: "APAC" },
  { code: "PL", label: "Poland", regionCode: "EMEA" },
  { code: "PT", label: "Portugal", regionCode: "EMEA" },
  { code: "PR", label: "Puerto Rico", regionCode: "LATAM" },
  { code: "QA", label: "Qatar", regionCode: "EMEA" },
  { code: "RE", label: "Réunion", regionCode: "EMEA" },
  { code: "RO", label: "Romania", regionCode: "EMEA" },
  { code: "RU", label: "Russian Federation", regionCode: "EMEA" },
  { code: "RW", label: "Rwanda", regionCode: "EMEA" },
  { code: "BL", label: "Saint Barthélemy", regionCode: "LATAM" },
  { code: "SH", label: "Saint Helena, Ascension and Tristan da Cunha", regionCode: "EMEA" },
  { code: "KN", label: "Saint Kitts and Nevis", regionCode: "LATAM" },
  { code: "LC", label: "Saint Lucia", regionCode: "LATAM" },
  { code: "MF", label: "Saint Martin (French part)", regionCode: "LATAM" },
  { code: "PM", label: "Saint Pierre and Miquelon", regionCode: "AMER" },
  { code: "VC", label: "Saint Vincent and the Grenadines", regionCode: "LATAM" },
  { code: "WS", label: "Samoa", regionCode: "APAC" },
  { code: "SM", label: "San Marino", regionCode: "EMEA" },
  { code: "ST", label: "Sao Tome and Principe", regionCode: "EMEA" },
  { code: "SA", label: "Saudi Arabia", regionCode: "EMEA" },
  { code: "SN", label: "Senegal", regionCode: "EMEA" },
  { code: "RS", label: "Serbia", regionCode: "EMEA" },
  { code: "SC", label: "Seychelles", regionCode: "EMEA" },
  { code: "SL", label: "Sierra Leone", regionCode: "EMEA" },
  { code: "SG", label: "Singapore", regionCode: "APAC" },
  { code: "SX", label: "Sint Maarten (Dutch part)", regionCode: "LATAM" },
  { code: "SK", label: "Slovakia", regionCode: "EMEA" },
  { code: "SI", label: "Slovenia", regionCode: "EMEA" },
  { code: "SB", label: "Solomon Islands", regionCode: "APAC" },
  { code: "SO", label: "Somalia", regionCode: "EMEA" },
  { code: "ZA", label: "South Africa", regionCode: "EMEA" },
  { code: "GS", label: "South Georgia and the South Sandwich Islands", regionCode: "LATAM" },
  { code: "SS", label: "South Sudan", regionCode: "EMEA" },
  { code: "ES", label: "Spain", regionCode: "EMEA" },
  { code: "LK", label: "Sri Lanka", regionCode: "APAC" },
  { code: "SD", label: "Sudan", regionCode: "EMEA" },
  { code: "SR", label: "Suriname", regionCode: "LATAM" },
  { code: "SJ", label: "Svalbard and Jan Mayen", regionCode: "EMEA" },
  { code: "SE", label: "Sweden", regionCode: "EMEA" },
  { code: "CH", label: "Switzerland", regionCode: "EMEA" },
  { code: "SY", label: "Syrian Arab Republic", regionCode: "EMEA" },
  { code: "TW", label: "Taiwan, Province of China", regionCode: "APAC" },
  { code: "TJ", label: "Tajikistan", regionCode: "APAC" },
  { code: "TZ", label: "Tanzania, United Republic of", regionCode: "EMEA" },
  { code: "TH", label: "Thailand", regionCode: "APAC" },
  { code: "TL", label: "Timor-Leste", regionCode: "APAC" },
  { code: "TG", label: "Togo", regionCode: "EMEA" },
  { code: "TK", label: "Tokelau", regionCode: "APAC" },
  { code: "TO", label: "Tonga", regionCode: "APAC" },
  { code: "TT", label: "Trinidad and Tobago", regionCode: "LATAM" },
  { code: "TN", label: "Tunisia", regionCode: "EMEA" },
  { code: "TR", label: "Türkiye", regionCode: "EMEA" },
  { code: "TM", label: "Turkmenistan", regionCode: "APAC" },
  { code: "TC", label: "Turks and Caicos Islands", regionCode: "LATAM" },
  { code: "TV", label: "Tuvalu", regionCode: "APAC" },
  { code: "UG", label: "Uganda", regionCode: "EMEA" },
  { code: "UA", label: "Ukraine", regionCode: "EMEA" },
  { code: "AE", label: "United Arab Emirates", regionCode: "EMEA" },
  { code: "GB", label: "United Kingdom of Great Britain and Northern Ireland", regionCode: "EMEA" },
  { code: "US", label: "United States of America", regionCode: "AMER" },
  { code: "UM", label: "United States Minor Outlying Islands", regionCode: "APAC" },
  { code: "UY", label: "Uruguay", regionCode: "LATAM" },
  { code: "UZ", label: "Uzbekistan", regionCode: "APAC" },
  { code: "VU", label: "Vanuatu", regionCode: "APAC" },
  { code: "VE", label: "Venezuela, Bolivarian Republic of", regionCode: "LATAM" },
  { code: "VN", label: "Viet Nam", regionCode: "APAC" },
  { code: "VG", label: "Virgin Islands (British)", regionCode: "LATAM" },
  { code: "VI", label: "Virgin Islands (U.S.)", regionCode: "LATAM" },
  { code: "WF", label: "Wallis and Futuna", regionCode: "APAC" },
  { code: "EH", label: "Western Sahara", regionCode: "EMEA" },
  { code: "YE", label: "Yemen", regionCode: "EMEA" },
  { code: "ZM", label: "Zambia", regionCode: "EMEA" },
  { code: "ZW", label: "Zimbabwe", regionCode: "EMEA" },
];
